apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: systemregister

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

configMapGenerator:
  - name: systemregister-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - ALLOWED_ORIGINS=https://systemregister.hovhas.se
