apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: systemregister-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: systemregister
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi

  - target:
      kind: IngressRoute
      name: systemregister
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`systemregister-dev.hovhas.se`)
      - op: replace
        path: /spec/tls/secretName
        value: systemregister-dev-tls

configMapGenerator:
  - name: systemregister-config
    behavior: replace
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - ALLOWED_ORIGINS=https://systemregister-dev.hovhas.se,http://localhost:5173
